version: '3.8'
name: bigcat
services:
  # Application service
  web:
    build:
      context: .
      args:
        requirements_file: requirements.txt
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - mongodb
    env_file: .env
    restart: always
    networks:
      - app-network

  # MongoDB Database
  mongodb:
    image: mongo:latest
    env_file: .env
    mem_limit: 512m
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: