name: Docker Image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    setps:
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: thomascedge/bigcat:latest
