name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/bigcat:$IMAGE_TAG \
            -t ${{ steps.login-ecr.outputs.registry }}/bigcat:latest \
            --push .
          echo "IMAGE=${{ steps.login-ecr.outputs.registry }}/bigcat:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Pull existing ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition bigcat-task \
            --query "taskDefinition" \
            --output json > ecs-task-def.json


      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          container-name: bigcat-app
          image: ${{ env.IMAGE }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: bigcat-service-1
          cluster: bigcat-cluster
          wait-for-service-stability: true
